##################################################################
##### WORKOUT #####

GET http://localhost:4000/api/workouts/ 
Content-Type: application/json

###

GET http://localhost:4000/api/workouts/6370aa7756cb371d090251e5
Content-Type: application/json

###

POST http://localhost:4000/api/workouts/
Content-Type: application/json

{
"title": "Bench press",
"load": 0,
"reps": 20
}

###

PATCH http://localhost:4000/api/workouts/6370aa7756cb371d090251e5
Content-Type: application/json

{
"reps": 50
}

###

DELETE http://localhost:4000/api/workouts/6370aa7756cb371d090251e5
Content-Type: application/json


##################################################################
##### USER #####

POST http://localhost:4000/api/user/login/
Content-Type: application/json

{
"email": "wigarfield@kmns.dev",
"password": "olala123"
}

###

POST http://localhost:4000/api/user/signup
Content-Type: application/json

{
"email": "wigarfield@jwt.dev",
"password": "@ol4lAoLil1"
}

###

POST http://localhost:4000/api/user/login
Content-Type: application/json

{
"email": "wigarfield@jwt.dev",
"password": "@ol4lAoLil1"
}
